// flow-typed signature: db535acb9ac0f42926fed23d04717781
// flow-typed version: <<STUB>>/kebab-case_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kebab-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kebab-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kebab-case/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kebab-case/index' {
  declare module.exports: $Exports<'kebab-case'>;
}
declare module 'kebab-case/index.js' {
  declare module.exports: $Exports<'kebab-case'>;
}
declare module 'kebab-case/test.js' {
  declare module.exports: $Exports<'kebab-case/test'>;
}
